config/routes.rb
Planet::Application.routes.draw do
  
  devise_for :users

  get "planet/index"

  get "planet/contact"

  resources :types do
    resources :sites
  end

  resources :sites do
    resources :comments
    collection do
      get 'search'
    end
  end
  
  resources :comments
  
  root :to => "planet#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :site
  belongs_to :user
  
  validates :body, :presence => true, :length => { :maximum => 140 }

end

app/models/site.rb
class Site < ActiveRecord::Base
  
  belongs_to :type
  belongs_to :user
  
  has_many :comments
  
  # Se añaden estas definiciones
  validates :name, :description, :type_id, :latitude, :longitude, :zoom, :image_url, :presence => true
  validates :zoom, :numericality => {:greater_than_or_equal_to => 0.1}
  validates :name, :uniqueness => true # Campo único (no repetido)
  
  # Debe estar protegido para evitar accesos indeseados
  attr_protected :user_id
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :sites
  
  # Se añade esta definición de recurso
  validates :name, :description, :presence => true # Asegura su presencia
  validates :name, :uniqueness => true # Campo único (no repetido)
end

app/models/user.rb
class User < ActiveRecord::Base
	
  has_many :sites
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_presence_of :name # El campo name se hace obligatorio

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    
    if current_user
      @site = Site.find(params[:site_id])
      params[:comment][:user_id] = current_user.id
    
      @comment = @site.comments.build(params[:comment])
    
      if @comment.save
        redirect_to site_path(@site)
      else
        redirect_to(@site, :notice => 'Error, comentario de mas de 140 caracteres')
      end
    else
      redirect_to new_user_session_path
    end
    
  end
  
  # GET /comments/1/edit
  def edit
    @comment = current_user.comments.find(params[:id])
    @site = Site.find(@comment.site_id)
  end
  
  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @comment = current_user.comments.find(params[:id])
    @site = Site.find(@comment.site_id)

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@site, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @comment = current_user.comments.find(params[:id])
    @site = Site.find(@comment.site_id)
    
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(@site, :notice => 'Comment was succesfully deleted.') }
      format.xml  { head :ok }
    end
  end
  
end

app/controllers/planet_controller.rb
class PlanetController < ApplicationController
  def index
  end

  def contact
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  
  before_filter :authenticate_user!, :except => [ :index, :show ]
  after_filter :count_visit, :only => :show
  
  # GET /sites
  # GET /sites.xml
  def index
    
    if params[:type_id].nil? or params[:type_id].empty?
      @sites = Site.all
      @titulo = 'Todos los Sitios'
    else
      @sites = Type.find(params[:type_id]).sites
      @titulo = Type.find(params[:type_id]).name
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = current_user.sites.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = current_user.sites.find(params[:id])
  end
  
  # GET /sites/search
  def search
    str = params[:search].to_s
    @sites = Site.where("name like ? or description like ?", "%#{str}%", "%#{str}%")
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site = current_user.sites.build(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to(@site, :notice => 'Site was successfully created.') }
        format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @site = current_user.sites.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to(@site, :notice => 'Site was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = current_user.sites.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  def count_visit
    @site.increment!(:visits)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.xml
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @types }
    end
  end

  # GET /types/1
  # GET /types/1.xml
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/new
  # GET /types/new.xml
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.xml
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to(@type, :notice => 'Type was successfully created.') }
        format.xml  { render :xml => @type, :status => :created, :location => @type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.xml
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to(@type, :notice => 'Type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.xml
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to(types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', site_path(@site) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Planet Travel Site</title>
    <!-- START:stylesheet -->
    <%= stylesheet_link_tag "scaffold" %>
    <%= stylesheet_link_tag "planet", :media => "all" %>
    <!-- END:stylesheet -->
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=false">
    // Carga la librería de Google Maps
    // Doc de Google Maps API: http://code.google.com/apis/maps/documentation/javascript/
    </script>
</head>

<body id="planet">

  <div id="banner">
    <%= image_tag("logo3.png") %>
    <%= @page_title || "Planet Travel Site" %>
    <div class="user">
      <% if current_user %>
        <%= link_to current_user.name, edit_user_registration_path %> |
        <%= link_to "Sign out", destroy_user_session_path %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
  </div>
  
  <div id="columns">
    <div id="side">
      <%= link_to "Home", planet_index_path %><br />
      <%= link_to "Tipos", types_path %><br />
      
      <!-- Enlaces a cada uno de los tipos -->
      <% Type.all.each do |type| %>
        <span class="sub_side"><%= link_to type.name, '/types/' + type.id.to_s + '/sites' %></span> <br />
      <% end %>
      
      <%= link_to "Sitios", sites_path %><br />
      <%= link_to "Contact", planet_contact_path %>
      <!-- Para buscar Sitios -->
      <div id="search_box">
        <%= form_tag(search_sites_path, :method => "get") do %>
          <%= text_field_tag(:search, params[:search]) %>
          <%= submit_tag("Search", :name => nil) %>
        <% end %>
      </div>
    </div>
    <div id="main">
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
</body>

</html>

app/views/planet/contact.html.erb
<h1>Contacting the Planet Travel Site</h1>
<p>
Please send an email to:
</p>

<p>
<a href="mailto:contact@planet.travel.com">contact@planet.travel.com</a> 
</p>

app/views/planet/index.html.erb
<h1>Welcome to the Planet Travel Site</h1>

<p>
This site gathers information
of touristic sites from all over
the world and should help you to
organize your trips and your holidays.
</p>

<%= image_tag('pedriza2-m.png') %>

<p>
Feel free to use it for your
convenience and pleasure.
</p>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 4 %>
  </div>
  <div class="field">
    <% types = Type.find(:all, :order => :name) %>
       <%= f.collection_select(:type_id, types, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :zoom %><br />
    <%= f.text_field :zoom %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div id="site_list">

  <h1><%= @titulo %> </h1>
 
  <table>
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
 
      <td>
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site %>
      </td>
 
      <td class="list_description">
        <dl>
          <dt><%= link_to site.name, site %></dt>
          <dd><%= truncate(strip_tags(site.description),
                 :length => 80) %></dd>
        </dl>
      </td>
 
      <td class="list_actions">
        <%= link_to 'Show', site %><br/>
        <% if site.user == current_user %>
          <%= link_to 'Edit', edit_site_path(site) %><br/>
          <%= link_to 'Destroy', site,
                    :confirm => 'Are you sure?',
                    :method => :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </table>
</div>
 
<br />
 
<%= link_to 'New site', new_site_path %>

app/views/sites/new.html.erb
<script type="text/javascript">

  $(function() {
    if (navigator.geolocation) { //Check if browser supports W3C Geolocation API
      navigator.geolocation.getCurrentPosition(successFunction, errorFunction);
    } else { 
      alert('Geolocation is not supported in this browser. Please enter position manually.'); 
    }
    function successFunction(position) {
        $("#site_latitude").val("" + position.coords.latitude);
        $("#site_longitude").val("" + position.coords.longitude);
    }
    function errorFunction(pos) { alert('Error!'); }
  });
  
</script>

<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/search.html.erb
<div id="site_list">

  <h1><%= @titulo %> </h1>
 
  <table>
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
 
      <td>
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site %>
      </td>
 
      <td class="list_description">
        <dl>
          <dt><%= link_to site.name, site %></dt>
          <dd><%= truncate(strip_tags(site.description),
                 :length => 80) %></dd>
        </dl>
      </td>
 
      <td class="list_actions">
        <%= link_to 'Show', site %><br/>
        <%= link_to 'Edit', edit_site_path(site) %><br/>
        <%= link_to 'Destroy', site,
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>
 
<br />

app/views/sites/show.html.erb
<p class="notice"><%= notice %></p>

<div id="site">
 
  <h1><%= @site.type.name if @site.type %></h1>

  <div id="col_info">
    <%= image_tag(@site.image_url, :class => 'site_image') %>
    <br />
    <h3 id="site_name" ><%= @site.name %></h3>

    <p><%=sanitize @site.description %></p>
    
    <p><b>Autor:</b> <%= @site.user.name %></p>
    
    <p />
    <div class="visits">
      <!-- Es la unica solucion que he encontrado a que salga una visita menos, puede que con reload... -->
      <em>Visits <%= @site.visits + 1 %></em>
    </div>
  </div>

  <div id="col_mapa">
    <!-- Aqui el mapa-->
    <div id="map_canvas"></div>
    
    <b>Latitude:</b>
    <span id="site_lat"><%= @site.latitude %></span>
    
    <b>Longitude:</b>
    <span id="site_lon"><%= @site.longitude %></span>
  </div>

</div>

<div id="comentarios">
  <h2>Comments</h2>
  <% @site.comments.each do |comment| %>
    <p>
      <b>Autor:</b>
      <%= User.find(comment.user_id).name %>
    </p>
   
    <p>
      <b>Comment:</b>
      <%= comment.body %>
    </p>
    <% if current_user && comment.user_id == current_user.id %>
      <%= link_to 'Edit', edit_comment_path(comment) %> |
      <%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
  <% end %>
</div>

<p class="erroralert"><%= notice %></p>

<h2>Add a comment:</h2>
<%= form_for([@site, @site.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% if @site.user == current_user %>
  <%= link_to 'Edit', edit_site_path(@site) %> |
<% end %>
<%= link_to 'Back', sites_path %>

<script type="text/javascript">
  $(function () {
    var latSitio = <%= @site.latitude %>;
    var lonSitio = document.getElementById('site_lon').innerHTML;
    var titleSitio = document.getElementById('site_name').innerHTML;

    // Store my position (“y=mylat”, “x=mylong”) in variable “lating”
    var latlng = new google.maps.LatLng(latSitio, lonSitio);

    // Define my Google Maps options in variable “myOptions”
    var myOptions = {
      zoom: 11, // Define scale
      center: latlng, // Define map center
      mapTypeId: google.maps.MapTypeId.ROADMAP // tipo Roadmad, Satellite, Terrain, Hybrid
    };

    // Load Google Map according to “myOptions” in Canvas identified by “map_canvas”
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    // Add marker in Google Maps “map” in position defined by “latlng”
    var marker = new google.maps.Marker({
      position: latlng,
      map: map,
      title: titleSitio
    });
  });
</script>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<div id="site_list">
  <h1>Listing Types</h1>
 
  <table>
  <% @types.each do |type| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
 
      <td class="list_description">
        <dl>
          <dt><%= link_to type.name, 'types/'+type.id.to_s+'/sites' %></dt>
          <dd><%= truncate(strip_tags(type.description),
                 :length => 80) %></dd>
        </dl>
      </td>
 
      <td class="list_actions">
        <%= link_to 'Show', type %><br/>
        <%= link_to 'Edit', edit_type_path(type) %><br/>
        <%= link_to 'Destroy', type,
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @type.description %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>